<script type="text/javascript">
	dojo.require('dojo.parser');
	dojo.require('dijit.form.Button');
	dojo.require('dijit.form.TextBox');
	dojo.require('dijit.form.Textarea');
	dojo.require('dijit.Dialog');
	dojo.require('dijit.InlineEditBox');
	loadSignatures();
	
	function addSignature() {
		dojo.xhrPost({
			url:		'/signatures/add/',
			handleAs:	'json',
			error: function(data, ioArgs) {
				alert('There was an error adding the signature');
			},
			load: function(data, ioArgs) {
				loadSignatures();
				dojo.byId('newSig').value = '';
			},
			content: {
				name: 	dojo.byId('newSig').value,
				type:	'implementation'
			}
		});
	}
	
	function loadSignatures() {
		dojo.xhrGet({
			url:	'/signatures/generate/type/implementation',
			load:	function(data, ioArgs) {
				dojo.byId('signatures').innerHTML = data;
			}
		});
		
	}
	
	function saveSection(section, id, text) {
		dojo.xhrPost({
				url: '/implementation/updatecell/',
				handleAs: 'json',
				load: function(data, ioArgs) {
					switch(section) {
						case 'completedBy':
							dojo.byId('status_' + id).innerHTML = (text == '' ? 'Incomplete' : 'Complete');
							break;
						case 'estimateCurrent':
						case 'elapsed':
							var est = dojo.byId('estimateCurrent_' + id).innerHTML;
							var elap = dojo.byId('elapsed_' + id).innerHTML;
							dojo.byId('remaining_' + id).innerHTML = est - elap;
							break;
					}
				},
				error: function(data, ioArgs) {
					alert('There was an error');
				},
				content: {
					'section': section,
					'id': id,
					'text': text
				}
			});
	}
</script>

<h1>Tasks for Implementation</h1>

<table>
	<thead>
		<tr>
			<th>Feature</th>
			<th>Priority</th>
			<th>Task</th>
			<th>Original Estimate</th>
			<th>Current Estimate</th>
			<th>Elapsed</th>
			<th>Remaining</th>
			<th>Status</th>
			<th>Completed By</th>
		</tr>
	</thead>
	<tbody>
		<?php if(count($this->tasks)): ?>
			<?php echo $this->partialLoop('implementation/_partials/task.phtml', $this->tasks); ?>
		<?php else: ?>
			<tr>
				<td colspan="9" align="center"><b>There are no tasks for this project.</b></td>
			</tr>
		<?php endif; ?>
	</tbody>
	<tfoot>
		<tr>
			<td colspan="9" align="right"><button dojoType="dijit.form.Button" onClick="dijit.byId('addTask').show();" style="float: right">Add Task</button></td>
		</tr>
	</tfoot>
</table>

<h2>Signatures</h2>
<div id="signatures">
</div>

<div id="addSig">
<label for="newSig">Name:</label><input type="text" name="newSig" id="newSig" dojoType="dijit.form.TextBox">
<button dojoType="dijit.form.Button" onClick="addSignature();">Add Signature</button>
</div>

<div id="addTask" title="Add New Task" dojoType="dijit.Dialog" style="text-align: left">
	<form method="POST" id="addTaskForm">
	<dl>
		<dt>Feature:</dt>
			<dd><input dojoType="dijit.form.TextBox" id="feature" name="feature"></dd>
		<dt>Priority:</dt>
			<dd><input dojoType="dijit.form.TextBox" id="priority" name="priority"></dd>
		<dt>Original Estimate:</dt>
			<dd><input dojoType="dijit.form.TextBox" id="estimateOrig" name="estimateOrig"></dd>
		<dt>Task:</dt>
			<dd><textarea dojoType="dijit.form.Textarea" id="task" name="task" style="width: 300px; height: 100px"></textarea></dd>
	</dl>
	
	<button dojoType="dijit.form.Button" style="float: right">
		Save Task
		<script type="dojo/method" event="onClick">
			dojo.xhrPost({
				url: '/implementation/addtask/',
				handleAs: 'json',
				load: function(data, ioArgs) {
					alert(data.message);

					if(data.status == 1) {
						window.location = "/implementation/";
					}
				},
				error: function(data, ioArgs) {
					alert('There was an error');
				},
				form: 'addTaskForm'
			});
		</script>
	</button>
		</form>
</div>