<script type="text/javascript">
    function deleteMessage(id)
    {
        $.ajax({
            dataType: "json",
            success: function(data, sts, rq) {
                $('#message-'+id).fadeOut();
            },
            url: "<?php echo $this->baseUrl(); ?>/messages/delete/messageId/"+id
        });
    }
</script>

<h1><?php echo $this->project->name; ?></h1>

<?php foreach($this->messages as $message): ?>
    <div class="user-message" id="message-<?php echo $message->id; ?>">
        <div class="container">
            <div class="author">
                <img src="http://www.gravatar.com/avatar/<?php echo md5($message->Message->Author->email); ?>?s=65&d=identicon" /><br />
            </div>

            <div class="meta">
                Created on <?php echo $message->Message->dateAdded; ?> <a href="javascript:deleteMessage(<?php echo $message->id; ?>);">(X)</a>
            </div>

            <div class="message">
                <a href="<?php echo $this->baseUrl().'/'.$message->Message->url; ?>"><?php echo $message->Message->message; ?></a>
            </div>
        </div>
    </div>
<?php endforeach; ?>