<h1><?php echo $this->project->name; ?></h1>

<?php foreach($this->messages as $message): ?>
    <div class="user-message">
        <div class="message">
            <a href="<?php echo $this->baseUrl().'/'.$message->Message->url; ?>"><?php echo $message->Message->message; ?></a>
        </div>
        <div class="meta">
            Created on <?php echo $message->Message->dateAdded; ?>
        </div>
<?php endforeach; ?>