<?php
$this->headTitle('Home');
$this->headScript()->captureStart();
?>

$(document).ready(function() {
	$.blockUI.defaults.applyPlatformOpacityRules = false;

	$('#addProjectButton').click(function() {
		$.blockUI({message: $('#addTaskDialog')});
	});

	$('#addProjectSubmit').click(function() {
		$.ajax({
			cache:	false,
			data:	{'name': $('#taskName').val()},
			success: function() {
				window.location = '<?php echo $baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl(); ?>';
			},
			type: 'POST',
			url: '<?php echo $baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl(); ?>/projects/addproject/'
		});

		return false;
	});

	$('#addProjectCancel').click(function() {
		$.unblockUI();
		return false;
	});
});

<?php
$this->headScript()->captureEnd();
?>
<h1>Projects</h1>

<ul>
	<?php echo $this->partialLoop('_partials/index/projectRow.phtml', $this->projects); ?>
</ul>
<input type="button" id="addProjectButton" value="Add New Project">

<div id="addTaskDialog" style="display: none">
<b>Project Name:</b><br />
<input type="text" name="taskName" id="taskName">

<p>
<input type="button" name="addProjectSubmit" id="addProjectSubmit" value="Add Project">
<input type="button" name="addProjectCancel" id="addProjectCancel" value="Cancel">
</div>