<?php

/**
 * Model_Base_Bug
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $project_id
 * @property string $title
 * @property string $description
 * @property string $reproduction
 * @property string $additionalInfo
 * @property integer $author_id
 * @property integer $assigned_id
 * @property timestamp $dateCreated
 * @property timestamp $dateClosed
 * @property integer $status_id
 * @property Model_Project $Project
 * @property Model_User $Author
 * @property Model_User $Assignee
 * @property Model_BugStatus $Status
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_Bug extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('bug');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('project_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('reproduction', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('additionalInfo', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('author_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('assigned_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('dateCreated', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('dateClosed', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('status_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_Project as Project', array(
             'local' => 'project_id',
             'foreign' => 'id'));

        $this->hasOne('Model_User as Author', array(
             'local' => 'author_id',
             'foreign' => 'id'));

        $this->hasOne('Model_User as Assignee', array(
             'local' => 'assigned_id',
             'foreign' => 'id'));

        $this->hasOne('Model_BugStatus as Status', array(
             'local' => 'status_id',
             'foreign' => 'id'));
    }
}