<?php

/**
 * Model_Base_Conversation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property integer $author_id
 * @property timestamp $dateAdded
 * @property timestamp $lastUpdated
 * @property integer $project_id
 * @property Model_Project $Project
 * @property Model_User $Author
 * @property Doctrine_Collection $ConversationPosts
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_Conversation extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('conversation');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('author_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('dateAdded', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('lastUpdated', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('project_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_Project as Project', array(
             'local' => 'project_id',
             'foreign' => 'id'));

        $this->hasOne('Model_User as Author', array(
             'local' => 'author_id',
             'foreign' => 'id'));

        $this->hasMany('Model_ConversationPost as ConversationPosts', array(
             'local' => 'id',
             'foreign' => 'conversation_id'));
    }
}