<?php

/**
 * Model_Base_TaskNote
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $task_id
 * @property string $note
 * @property timestamp $dateAdded
 * @property integer $author_id
 * @property Model_User $Author
 * @property Model_Task $Task
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_TaskNote extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('task_note');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('task_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('note', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('dateAdded', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('author_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_User as Author', array(
             'local' => 'author_id',
             'foreign' => 'id'));

        $this->hasOne('Model_Task as Task', array(
             'local' => 'task_id',
             'foreign' => 'id'));
    }
}