<script type="text/javascript">

$(document).ready(function() {
	$('#newEmail').change(function() {
		$.ajax({
			data:		{ email: $('#newEmail').val() },
			dataType:	'json',
			error:		function(rq, status, error) {
				alert('There was a problem searching for the user: ' + error);
			},
			success:	function(rsp, status) {
				$('#newName').val(rsp.name);
				$('#existingId').val(rsp.id);
			},
			type:		'POST',
			url:		'<?php echo $this->baseUrl(); ?>/teams/search/'
		});
	});

	$('#addTeamMemberButton').click(function() {
		$('#addNewTeamMemberDialog').dialog('open');
	});

	$('#addNewTeamMemberDialog').dialog({
		bgiframe:	true,
		autoOpen:	false,
		modal:		true,
		buttons:	{
			'Add Team Member': function() {
				$.ajax({
					data:		{
						email:	$('#newEmail').val(),
						name:	$('#newName').val(),
						id:	 	$('#existingId').val()
					},
					dataType:	'json',
					error:		function(rq, status, error) {
						alert('There was a problem searching for the user: ' + error);
					},
					success:	function(rsp, status) {
						if(rsp.status == 1) {
							$('#addNewTeamMemberDialog').dialog('close');
							alert('New Team Member Added');
							$('#newName').val("");
							$('#existingId').val("");
							$('#newEmail').val("");
						} else if(rsp.status == -1) {
							alert('This user is already a member of this project.');
						} else {
							alert('There was a problem adding the member to the team.');
						}
					},
					type:		'POST',
					url:		'<?php echo $this->baseUrl(); ?>/teams/add/'
				});
			}
		}
	});
});

</script>

<h1>Project Configuration</h1>

<h2>Project Details</h2>
<form method="post" action="<?php echo $this->baseUrl(); ?>/configuration/save">
<dl>
	<dt>Project Name:</dt>
		<dd><input type="text" name="name" id="name" value="<?php echo $this->name; ?>" style="width: 300px"></dd>
	<dt>Project Description:</dt>
		<dd><textarea name="description" id="description" style="width: 300px; height: 200px;"><?php echo $this->description; ?></textarea></dd>
</dl>
</form>

<h2>Team Members</h2>
<table>
	<thead>
		<tr>
			<th>Name</th>
			<th>E-Mail Address</th>
			<th>Remove</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->teamMembers as $member): ?>
			<tr>
				<td><a href="mailto:<?php echo $member->email; ?>"><?php echo $member->name; ?></a></td>
				<td><a href="mailto:<?php echo $member->email; ?>"><?php echo $member->email; ?></a></td>
				<td class="center"><a href="#" onClick="removeTeamMember(<?php $member->id ?>)">X</a></td>
			</tr>
		<?php endforeach; ?>
	</tbody>
	<tfoot>
		<tr>
			<td colspan="3" class="right"><button id="addTeamMemberButton" name="addTeamMemberButton">New Team Member</button></td>
		</tr>
	</tfoot>
</table>

<div id="addNewTeamMemberDialog" title="Add New Team Member" class="left">
	<form>
		<fieldset>
			<dl>
				<dt>E-mail Address:</dt>
					<dd><input type="text" name="newEmail" id="newEmail" class="text ui-widget ui-corner-all" /></dd>
				<dt>Name:</dt>
					<dd><input type="text" name="newName" id="newName" class="text ui-widget ui-corner-all" /></dd>
			</dl>
			<input type="hidden" name="existingId" id="existingId" value="" />
		</fieldset>
	</form>
</div>