<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery/jquery.expander.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/tiny_mce/tiny_mce.js"></script>


<script type="text/javascript">
function addNote(section) {
	$('#section').val(section);
	$('#addNoteDialog').dialog('open');

	tinyMCE.execCommand('mceAddControl', true, 'text');
}

tinyMCE.init({
	mode:								'none',
	theme:								'advanced',
	theme_advanced_toolbar_location:	'top',
	theme_advanced_toolbar_align:		'left',
	theme_advanced_statusbar_location:	'bottom',
	theme_advanced_buttons1:			'bold,italic,underline,strikethrough,separator,bullist,numlist,undo,redo,link,unlink',
	theme_advanced_buttons2:			'',
	theme_advanced_buttons3:			'',
	theme_advanced_resizing:			true
});

$(document).ready(function() {
	$('ul.expandable div.noteText').expander();

	$('#addNoteDialog').dialog({
        bgiframe:   true,
        autoOpen:   false,
        modal:      true,
		width:      725,
        buttons:    {
            'Add Note':  function() {
                $.ajax({
                   data:   {
                        title:		$('#title').val(),
                        //text:		$('#text').val(),
                        text:		tinyMCE.get('text').getContent(),
                        section:	$('#section').val()
                    },
                    dataType:   'json',
                    success:    function(rsp, status) {
                        if(rsp.status == 1) {
                            window.location = '<?php echo $this->baseUrl(); ?>/notes';
                        } else {
                            alert('There was a problem adding the note. Please contact tech support.');
                        }
                    },
                    type:       'POST',
                    url:        '<?php echo $this->baseUrl();?>/notes/add/'
                });
            }
        }
    });
});
</script>

<h1>Notes for '<?php echo $this->projectName ?>'</h1>

<h2>Software Design</h2>
<ul class="expandable">
	<?php foreach($this->notes as $note): ?>
		<li>
			<div class="noteTitle"><?php echo $note->title; ?></div>
			<div class="noteText"><?php echo $note->text; ?></div>
		</li>
	<?php endforeach; ?>
</ul>

<button onClick="addNote('sdd');">Add Note</button>

<div id="addNoteDialog" class="left" title="Add New Note">
<dl>
	<dt>Title:</dt>
		<dd><input type="text" name="title" id="title"></dd>
	<dt>Text:</dt>
		<dd><textarea name="text" id="text"></textarea></dd>
</dl>
<input type="hidden" id="section" value="">
</div>