<script type="text/javascript">
	dojo.require('dijit.form.Button');
	dojo.require('dijit.form.TextBox');
	loadSignatures();
	
	function addSignature() {
		dojo.xhrPost({
			url:		'/signatures/add/',
			handleAs:	'json',
			error: function(data, ioArgs) {
				alert('There was an error adding the signature');
			},
			load: function(data, ioArgs) {
				loadSignatures();
				dojo.byId('newSig').value = '';
			},
			content: {
				name: 	dojo.byId('newSig').value,
				type:	'design'
			}
		});
	}
	
	function loadSignatures() {
		dojo.xhrGet({
			url:	'/signatures/generate/type/design',
			load:	function(data, ioArgs) {
				dojo.byId('signatures').innerHTML = data;
			}
		});
		
	}
</script>
<h1>Design Documents for '<?php echo $this->projectName; ?>'</h1>

<p>
At this time, this section just allows you to sign off that the Design procedure has been finished. Eventually documents will be able to be uploaded and reviewed from here.
</p>

<p>
For the time being, once all Design process has been finished offline, please sign off on this section to move on to Implementation.
</p>

<h2>Signatures</h2>
<div id="signatures">
</div>

<div id="addSig">
<label for="newSig">Name:</label><input type="text" name="newSig" id="newSig" dojoType="dijit.form.TextBox">
<button dojoType="dijit.form.Button" onClick="addSignature();">Add Signature</button>
</div>

