<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
 "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
    <?php echo $this->headTitle(); ?>
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/yui/reset-fonts-grids.css">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/yui/base-min.css">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/layout.css">
</head>
<body class="tundra">
<div id="doc3" class="yui-t2">
	<div id="hd">
		<div style="float: right; color: white">
			<a href="<?php echo $this->baseUrl(); ?>/admin/">Admin Home</a> |
			<a href="<?php echo $this->baseUrl(); ?>/auth/index/logout">Log Out</a>
		</div>

		<h1><a href="<?php echo $this->baseUrl(); ?>/">Congregate Project Manager</a></h1>
	</div>
	<div id="bd">
		<div id="yui-main">
			<div class="yui-b">
				<div class="yui-g" id="content">
					<!-- YOUR DATA GOES HERE -->
					<?php echo $this->layout()->content; ?>
				</div>
			</div>
		</div>
		<div class="yui-b" id="navigation">
			<!-- Navigation -->
			<ul>
				<li><a href="<?php echo $this->baseUrl(); ?>/admin/projects">Projects</a></li>
				<li><a href="<?php echo $this->baseUrl(); ?>/admin/users">Users and Groups</a></li>
			</ul>
		</div>
	</div>
	<div id="ft"><p>Copyright 2009 <a href="http://www.tankersleywebsolutions.com">Chris Tankersley</a></p></div>
</div>
</body>
</html>
