<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
 "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
	<title>Biff ProjectManager</title>
	<link rel="stylesheet" href="http://yui.yahooapis.com/2.7.0/build/reset-fonts-grids/reset-fonts-grids.css" type="text/css">
	<link rel="stylesheet" href="/js/dojo-release-1.2.3/dijit/themes/tundra/tundra.css" type="text/css">
	<link rel="stylesheet" href="/js/dojo-release-1.2.3/dojo/resources/dojo.css" type="text/css">
	
	<script type="text/javascript" src="/js/dojo-release-1.2.3/dojo/dojo.js" djConfig="parseOnLoad: true"></script>
</head>
<body class="tundra">
<div id="doc3" class="yui-t7">
	<div id="hd"><h1><a href="/">BPM</a></h1></div>
	<div id="bd">
		<div class="yui-g">
			<!-- YOUR DATA GOES HERE -->
			<?php echo $this->layout()->content; ?>
		</div>
	</div>
	<div id="ft"><p>Copyright 2009 <a href="http://www.tankersleywebsolutions.com">Chris Tankersley</a></p></div>
</div>
</body>
</html>
