<?php

/**
 * Model_Message
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_Message extends Model_Base_Message
{
    /**
     *
     * @param string $text
     * @param string $url
     * @param Model_User $author
     * @param Model_Project $project
     */
    static public function addMessage($text, $url, $author, $project)
    {
        $message = new Model_Message();
        $message->message = $text;
        $message->url = $url;
        $message->author_id = $author;
        $message->dateAdded = date('Y-m-d H:i:s');
        $message->save();

        foreach($project->UserProjects as $up) {
            $userMessage = new Model_UserMessages();
            $userMessage->message_id = $message->id;
            $userMessage->user_id = $up->user_id;
            $userMessage->project_id = $project;
            $userMessage->save();
        }

        $message->UserMessages->save();
    }
}