<h1>Bugs</h1>

<table>
    <thead>
        <tr>
            <th>Bug ID</th>
            <th>Title</th>
            <th>Reported By</th>
            <th>Reported On</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        <?php if(count($this->bugs)): ?>
            <?php foreach($this->bugs as $bug): ?>
                <tr>
                    <td><a href="<?php echo $this->baseUrl(); ?>/project/bugs/view/bug/<?php echo $bug->id; ?>"><?php echo str_pad($bug->id, 6, '0', STR_PAD_LEFT); ?></a></td>
                    <td><?php echo $bug->title; ?></td>
                    <td><?php echo $bug->Author->name; ?></td>
                    <td><?php echo $bug->dateCreated; ?></td>
                    <td><?php echo $bug->Status->title; ?></td>
                </tr>
            <?php endforeach; ?>
        <?php else: ?>
            <tr>
                <td colspan="5" align="center"><b>There are no bugs reported</b></td>
            </tr>
        <?php endif; ?>
    </tbody>
    <tfoot>
        <tr>
            <td colspan="5" align="right"><a href="<?php echo $this->baseUrl(); ?>/project/bugs/create">Report New Bug</a></td>
        </tr>
    </tfoot>
</table>