<h1>View Bug: <?php echo $this->bug->title; ?></h1>

<table>
    <tbody>
        <tr>
            <th>Bug ID:</th>
            <td><?php echo str_pad($this->bug->id, 6, '0', STR_PAD_LEFT); ?></td>
        </tr>
        <tr>
            <th>Title:</th>
            <td><?php echo $this->bug->title; ?></td>
        </tr>
        <tr>
            <th>Description:</th>
            <td><?php echo $this->bug->description; ?></td>
        </tr>
        <tr>
            <th>How to Reproduce:</th>
            <td><?php echo $this->bug->reproduction; ?></td>
        </tr>
        <tr>
            <th>Additional Info:</th>
            <td><?php echo $this->bug->additionalInfo; ?></td>
        </tr>
        <tr>
            <th>Assigned To:</th>
            <td><?php echo $this->bug->Assignee->name; ?></td>
        </tr>
        <tr>
            <th>Reported By:</th>
            <td><?php echo $this->bug->Author->name; ?></td>
        </tr>
        <tr>
            <th>Reported On:</th>
            <td><?php echo $this->bug->dateCreated; ?></td>
        </tr>
        <tr>
            <th>Current Status:</th>
            <td><?php echo $this->bug->Status->title; ?></td>
        </tr>
    </tbody>
</table>