<h1>Users and Groups Administration</h1>

<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Real Name</th>
            <th>Username</th>
            <th>E-mail</th>
            <th>Status</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->users as $user): ?>
            <tr>
                <td><?php echo $user->id; ?></td>
                <td><?php echo $user->name; ?></td>
                <td><?php echo $user->username; ?></td>
                <td><?php echo $user->email; ?></td>
                <td><?php echo $user->status; ?></td>
                <td>Delete | Re-Auth</td>
            </tr>
        <?php endforeach; ?>
    </tbody>
    <tfoot>
        <tr>
            <td colspan="6" align="right"><a href="<?php echo $this->baseUrl(); ?>/admin/users/add">Add New User</a></td>
        </tr>
    </tfoot>
</table>