<script type="text/javascript">
	dojo.require('dojo.parser');
	dojo.require('dijit.InlineEditBox');
	dojo.require('dijit.Editor');
	
	function saveSection(section, text) {
		dojo.xhrPost({
				url: '/projects/sddsave/',
				handleAs: 'json',
				error: function(data, ioArgs) {
					alert('There was an error');
				},
				content: {
					'section': section,
					'text': text,
					'project': <?php echo $this->projectId; ?>
				}
			});
	}
</script>
<h1>Software Design Description for '<?php echo $this->projectName; ?>'</h1>

<h2>Introduction</h2>
<h3>Design Overview</h3>
<p id="designOverview" dojoType="dijit.InlineEditBox" editor="dijit.Editor" renderAsHTML="true" buttonSave="Save" onChange="saveSection('designOverview', arguments[0]);" autosave="false">
	<?php echo ($this->designOverview == '' ? 'No Text Supplied' : $this->designOverview); ?>
</p>

<h2>System Architecture Design</h2>
<h3>Chosen System Architecture</h3>
<p id="chosenArchitecture" dojoType="dijit.InlineEditBox" editor="dijit.Editor" renderAsHTML="true" buttonSave="Save" onChange="saveSection('chosenArchitecture', arguments[0]);" autosave="false">
	<?php echo ($this->chosenArchitecture == '' ? 'No Text Supplied' : $this->chosenArchitecture); ?>
</p>

<h3>Discussion of Alternate Designs</h3>
<p id="alternateDesigns" dojoType="dijit.InlineEditBox" editor="dijit.Editor" renderAsHTML="true" buttonSave="Save" onChange="saveSection('alternateDesigns', arguments[0]);" autosave="false">
	<?php echo ($this->alternateDesigns == '' ? 'No Text Supplied' : $this->alternateDesigns); ?>
</p>

<h3>System Interface Description</h3>
<p id="systemInterfaceDescription" dojoType="dijit.InlineEditBox" editor="dijit.Editor" renderAsHTML="true" buttonSave="Save" onChange="saveSection('systemInterfaceDescription', arguments[0]);" autosave="false">
	<?php echo ($this->systemInterfaceDescription == '' ? 'No Text Supplied' : $this->systemInterfaceDescription); ?>
</p>

<h2>Detailed Description of Components</h2>
<h3>Coming Soon</h3>

<h2>User Interface Design</h2>
<h3>Description of User Interface</h3>
<p id="userInterfaceDescription" dojoType="dijit.InlineEditBox" editor="dijit.Editor" renderAsHTML="true" buttonSave="Save" onChange="saveSection('userInterfaceDescription', arguments[0]);" autosave="false">
	<?php echo ($this->userInterfaceDescription == '' ? 'No Text Supplied' : $this->userInterfaceDescription); ?>
</p>

<h2>Additional Material</h2>
<p id="additionalMaterial" dojoType="dijit.InlineEditBox" editor="dijit.Editor" renderAsHTML="true" buttonSave="Save" onChange="saveSection('additionalMaterial', arguments[0]);" autosave="false">
	<?php echo ($this->additionalMaterial == '' ? 'No Text Supplied' : $this->additionalMaterial); ?>
</p>