<script type="text/javascript">
	var sigCount = 0;
	
	dojo.require('dojo.parser');
	dojo.require('dijit.InlineEditBox');
	dojo.require('dijit.Editor');
	dojo.require('dijit.form.Button');
	dojo.require('dijit.form.TextBox');
	loadSignatures();
	
	function addSignature() {
		dojo.xhrPost({
			url:		'/projects/addsddsignature/',
			handleAs:	'json',
			error: function(data, ioArgs) {
				alert('There was an error adding the signature');
			},
			load: function(data, ioArgs) {
				loadSignatures();
				dojo.byId('newSig').value = '';
			},
			content: {
				name: dojo.byId('newSig').value,
				projectId:	<?php echo $this->projectId; ?>
			}
		});
	}
	
	function loadSignatures() {
		dojo.xhrGet({
			url:	'/projects/generatesddsignatures/project/<?php echo $this->projectId; ?>',
			load:	function(data, ioArgs) {
				dojo.byId('signatures').innerHTML = data;
			}
		});
		
	}
	
	function saveSection(section, text) {
		dojo.xhrPost({
				url: '/projects/sddsave/',
				handleAs: 'json',
				error: function(data, ioArgs) {
					alert('There was an error');
				},
				content: {
					'section': section,
					'text': text,
					'project': <?php echo $this->projectId; ?>
				}
			});
	}
</script>
<h1>Software Design Description for '<?php echo $this->projectName; ?>'</h1>

<h2>1. Introduction</h2>
	<blockquote>
		<h3>1. Design Overview</h3>
		<blockquote>
			<p id="designOverview" dojoType="dijit.InlineEditBox" editor="dijit.Editor" renderAsHTML="true" buttonSave="Save" onChange="saveSection('designOverview', arguments[0]);" autosave="false">
				<?php echo ($this->designOverview == '' ? 'No Text Supplied' : $this->designOverview); ?>
			</p>
		</blockquote>
	</blockquote>

<h2>2. System Architecture Design</h2>
	<blockquote>
		<h3>1. Chosen System Architecture</h3>
		<blockquote>
			<p id="chosenArchitecture" dojoType="dijit.InlineEditBox" editor="dijit.Editor" renderAsHTML="true" buttonSave="Save" onChange="saveSection('chosenArchitecture', arguments[0]);" autosave="false">
				<?php echo ($this->chosenArchitecture == '' ? 'No Text Supplied' : $this->chosenArchitecture); ?>
			</p>
		</blockquote>

		<h3>2. Discussion of Alternate Designs</h3>
		<blockquote>
			<p id="alternateDesigns" dojoType="dijit.InlineEditBox" editor="dijit.Editor" renderAsHTML="true" buttonSave="Save" onChange="saveSection('alternateDesigns', arguments[0]);" autosave="false">
				<?php echo ($this->alternateDesigns == '' ? 'No Text Supplied' : $this->alternateDesigns); ?>
			</p>
		</blockquote>

		<h3>3. System Interface Description</h3>
		<blockquote>
			<p id="systemInterfaceDescription" dojoType="dijit.InlineEditBox" editor="dijit.Editor" renderAsHTML="true" buttonSave="Save" onChange="saveSection('systemInterfaceDescription', arguments[0]);" autosave="false">
				<?php echo ($this->systemInterfaceDescription == '' ? 'No Text Supplied' : $this->systemInterfaceDescription); ?>
			</p>
		</blockquote>
	</blockquote>

<h2>3. Detailed Description of Components</h2>
	<blockquote>
		<h3>Coming Soon</h3>
	</blockquote>

<h2>4. User Interface Design</h2>
	<blockquote>
		<h3>1. Description of User Interface</h3>
		<p id="userInterfaceDescription" dojoType="dijit.InlineEditBox" editor="dijit.Editor" renderAsHTML="true" buttonSave="Save" onChange="saveSection('userInterfaceDescription', arguments[0]);" autosave="false">
			<?php echo ($this->userInterfaceDescription == '' ? 'No Text Supplied' : $this->userInterfaceDescription); ?>
		</p>
	</blockquote>

<h2>5. Additional Material</h2>
	<blockquote>
		<p id="additionalMaterial" dojoType="dijit.InlineEditBox" editor="dijit.Editor" renderAsHTML="true" buttonSave="Save" onChange="saveSection('additionalMaterial', arguments[0]);" autosave="false">
			<?php echo ($this->additionalMaterial == '' ? 'No Text Supplied' : $this->additionalMaterial); ?>
		</p>
	</blockquote>
	

<h2>Signatures</h2>
<div id="signatures">
</div>

<div id="addSig">
<label for="newSig">Name:</label><input type="text" name="newSig" id="newSig" dojoType="dijit.form.TextBox">
<button dojoType="dijit.form.Button" onClick="addSignature();">Add Signature</button>
</div>

