<h1>Issues</h1>

<table>
    <thead>
        <tr>
            <th>Issue ID</th>
            <th>Title</th>
            <th>Reported By</th>
            <th>Reported On</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        <?php if(count($this->issues)): ?>
            <?php foreach($this->issues as $issue): ?>
                <tr>
                    <td><a href="<?php echo $this->baseUrl(); ?>/project/issues/view/issue/<?php echo $issue->id; ?>"><?php echo str_pad($issue->id, 6, '0', STR_PAD_LEFT); ?></a></td>
                    <td><?php echo $issue->title; ?></td>
                    <td><?php echo $issue->Author->name; ?></td>
                    <td><?php echo $issue->dateCreated; ?></td>
                    <td><?php echo $issue->Status->title; ?></td>
                </tr>
            <?php endforeach; ?>
        <?php else: ?>
            <tr>
                <td colspan="5" align="center"><b>There are no issues reported</b></td>
            </tr>
        <?php endif; ?>
    </tbody>
    <tfoot>
        <tr>
            <td colspan="5" align="right"><a href="<?php echo $this->baseUrl(); ?>/project/issues/create">Report New Issue</a></td>
        </tr>
    </tfoot>
</table>