<tr>
	<td valign="top">
		<div id="feature_<?php echo $this->id; ?>" class="edit"><?php echo $this->feature; ?></div>
	</td>
	<td valign="top" align="center">
		<div id="priority_<?php echo $this->id; ?>" class="edit"><?php echo $this->priority; ?></div>
	</td>
	<td valign="top">
		<div id="task_<?php echo $this->id; ?>" class="edit_area"><?php echo $this->task; ?></div>
	</td>
	<td valign="top" align="center"><?php echo $this->estimateOrig; ?></td>
	<td valign="top" align="center">
		<div id="estimateCurrent_<?php echo $this->id; ?>" class="edit"><?php echo $this->estimateCurrent; ?></div>
	</td>
	<td valign="top" align="center">
		<div id="elapsed_<?php echo $this->id; ?>" class="edit"><?php echo $this->elapsed; ?></div>
	</td>
	<td valign="top" align="center">
		<div id="remaining_<?php echo $this->id; ?>"><?php echo $this->remaining; ?></div>
	</td>
	<td valign="top" align="center">
		<div id="status_<?php echo $this->id; ?>"><?php echo ($this->status ? 'Complete' : 'Incomplete'); ?></div>
	</td>
	<td valign="top">
		<?php echo date('m/d/Y', strtotime($this->dateCreated)); ?>
	</td>
	<td valign="top">
		<?php echo ($this->status ? date('m/d/Y', strtotime($this->dateCompleted)) : ''); ?>
	</td>
	<td valign="top">
		<div id="completedBy_<?php echo $this->id; ?>" class="edit"><?php echo $this->completedBy; ?></div>
	</td>
</tr>