options:
  type: INNODB
  collate: utf8_general_ci
  charset: utf8

Project:
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    name: string(255)
    description: text
    status: tinyint
    authorId: integer
    dateCreated: timestamp
    dateApproved: timestamp
    dateDeclined: timestamp
    dateCompleted: timestamp
  actAs:
    Sluggable:
      unique: true
      fields: [id, name]
      canUpdate: true
  relations:
    User:
      local: authorId
      foreign: id
    Users:
      foreignAlias: Projects
      class: User
      refClass: UserProjects

User:
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    username:
      type: string(255)
      unique: true
    password: string(255)
    name: string(255)
    email:
      type: string(255)
      unique: true
    primaryGroup: integer
    dateCreated: 
      type: timestamp
    dateActivated: timestamp
    status: tinyint
    challenge: string(50)

UserProjects:
  columns:
      id:
        type: integer
        primary: true
        autoincrement: true
      user_id: integer
      project_id: integer
  relations:
    Project:
      foreignAlias: UserProjects
    User:
      foreignAlias: UserProjects

Task:
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    project_id: integer
    parent_id: integer
    title: string(255)
    description: string
    dateAdded: date
    deadline: date
    author_id: integer
    assignedTo: integer
    status: tinyint
  relations:
    Project:
      foreignAlias: Tasks
    Author:
      class: User
      local: author_id
      foreign: id

TaskNote:
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    task_id: integer
    note: string
    dateAdded: timestamp
    author_id: integer
  relations:
    Author:
      class: User
      local: author_id
      foreign: id
    Task:
      local: task_id
      foreign: id
      foreignAlias: Notes

Bug:
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    project_id: integer
    title: string(255)
    description: string
    reproduction: string
    additionalInfo: string
    author_id: integer
    assigned_id: integer
    dateCreated: timestamp
    dateClosed: timestamp
    status_id: integer
  relations:
    Project:
      local: project_id
      foreign: id
      foreignAlias: Bugs
    Author:
      class: User
      local: author_id
      foreign: id
    Assignee:
      class: User
      local: assigned_id
      foreign: id
    Status:
      class: BugStatus
      local: status_id
      foreign: id

BugStatus:
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    title: string(255)