options:
  type: INNODB
  collate: utf8_general_ci
  charset: utf8

User:
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    username:
      type: string(255)
      unique: true
    password: string(255)
    name: string(255)
    email:
      type: string(255)
      unique: true
    primaryGroup: integer
    dateCreated: 
      type: timestamp
    dateActivated: timestamp
    status: tinyint
    challenge: string(50)

Project:
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    name: string(255)
    description: text
    status: tinyint
    author: integer
    dateCreated: timestamp
    dateApproved: timestamp
    dateDeclined: timestamp
    dateCompleted: timestamp
  actAs:
    Sluggable:
      unique: true
      fields: [id, name]
      canUpdate: true